### ISSUE TITLE
project.version out of date?

### ISSUE THREAD

**Issue by tracylynne99** [jfree/jfreechart#239]
In src/main/java/org/jfree/chart/resources/JFreeChartResources.java, is the project.version supposed to match the current release? If so, 1.0.18 is very out of date! :-)

**Comment by trashgod** [comment]
For reference, the file was renamed [here](https://github.com/jfree/jfreechart/commit/2228e7e92f418078706f2134d2ecce11888b1cb7) and deleted [here](https://github.com/jfree/jfreechart/commit/3c41759a7e9850998ded301235b0ad7a1866a43b). This appears to be the last [change](https://github.com/jfree/jfreechart/commit/69e83d6675375ebb0b249e66b880cdb998bfda95#diff-562ac7c6a2c3e213511d3e99da7c59e72a20ef2cf1814dfe5898d75ae75e7889).

**Comment by jfree** [comment]
Hi Tracy,  Good spot, I'll update that on the 1.5.x branch.  In fact the file has no real purpose anymore, so that's why it is gone from the master branch.  Once upon a time, I included some code where you could print out the library version by running java -jar jfreechart.jar or something, but that's no longer in there, so this class doesn't really do anything.  I'll remove it.
