### ISSUE TITLE
can it generate an image with a restful api

### ISSUE THREAD

**Issue by WilkinWendy** [jfree/jfreechart#290]
My requirement is to get a image of chart from requesting api with params

**Comment by trashgod** [comment]
Not sure about the API, but [`org.jfree.chart.ChartUtils`](https://www.jfree.org/jfreechart/javadoc/org/jfree/chart/ChartUtils.html) supports several common image formats.

**Comment by jfree** [comment]
JFreeChart does not provide restful api mechanisms, just the chart creation framework and tools to support conversion to various formats.

**Comment by gk-brown** [comment]
I know this ticket is closed, but rather than creating a new one I thought I would just comment here. It seems that JFreeChart does indeed support headless operation, but it is not very well documented (there is literally no mention of "headless" in the developer guide). 

I imagine this would be a common use case, so it would be nice to see some examples in the guide. The Swing examples are helpful, but I would guess (although perhaps incorrectly) that JFreeChart is being used more often on the server than the client at this point?

**Comment by trashgod** [comment]
This [Q&A](https://stackoverflow.com/q/13984381/230513) may offer some guidance.

**Comment by gk-brown** [comment]
Thank you, I have seen that. Not looking for assistance - just suggesting that the developer guide should contain some information about using the framework in a headless context.
