### ISSUE TITLE
Missing Source

### ISSUE THREAD

**Issue by gmcfadden1** [jfree/jfreechart#90]
In the master branch, where is the StackedBarRenderer3D? It appears to be missing. It should be in org.jfree...chart.renderer

**Comment by jfree** [comment]
The master branch contains the code for JFreeChart 1.5.x, and in that release I have removed all the fake 3D classes because it complicates the code and better options exist for 3D charts (Orson Charts for example).

There is a branch for version 1.0.x where you can still find the classes if you really need them.
