### ISSUE TITLE
Automatic module name

### ISSUE THREAD

**Issue by TheBoegl** [jfree/jfreechart#97]
As described by [Mak Sander](http://branchandbound.net/blog/java/2017/12/automatic-module-name/) we should add the automatic module name entries to the manifest. 
This would really help in jdk9 builds using this library.

**Comment by TheBoegl** [comment]
Though to work as module, we should get rid of the split packages and move the package org.jfree.data to a separate library.

**Comment by jfree** [comment]
Is it required?  Does something about the module system prohibit org.jfree.chart and org.jfree.data packages in the same module?  I haven't spent much time looking at the module system yet, doing that now :-)

**Comment by jfree** [comment]
I've seen a suggestion that the automatic module name should be the same as the top-most package (for example, org.jfree.chart) and I see how that creates a conflict with the package org.jfree.date.  However, this seems to be a suggestion rather than a requirement.  JFreeChart 1.5.1 is released with the automatic module name org.jfree.jfreechart (which doesn't match any package but is pretty much guaranteed to be unique).  

A future version of JFreeChart (probably JFreeChart 2) will be a first class module, and most likely have a different module name.  But that's for later.  Since JFreeChart 1.5.1 has an automatic module name, I'll close this bug.
